version: "3.3"

services:
  primarydb:
    image: postgres:12.13
    restart: always

    environment:
      POSTGRES_PASSWORD: shop
      POSTGRES_USER: shop_user
      POSTGRES_DB: shop_db
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - 32432:5432
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  
  web:
    build:
      context: .
      dockerfile: ./ci/Dockerfile.prod
    command: 'poetry run gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000'
    environment:
      DB_HOST: primarydb
      DB_PORT: 5432
      DB_USERNAME: shop_user
      DB_PASSWORD: shop
      DB_DATABASES: shop_db
      BROKER_PORT: 6379
      BROKER_HOST: redis
    volumes:
      - .:/usr/src/app
      
    ports:
      - 8000:8000
  
  celery:
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    command: 'poetry run celery -A main.celery worker --loglevel=info -P gevent'
    environment:
      DB_HOST: primarydb
      DB_PORT: 5432
      DB_USERNAME: shop_user
      DB_PASSWORD: shop
      DB_DATABASES: shop_db
      BROKER_PORT: 6379
      BROKER_HOST: redis
    volumes:
      - .:/usr/src/app
  
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data: